services:
  db:
    image: postgres:17
    container_name: posada_db
    environment:
      POSTGRES_USER: posadmin
      POSTGRES_PASSWORD: posada123
      POSTGRES_DB: posada
    ports:
      - "5432:5432"
    volumes:
      - posada_pgdata:/var/lib/postgresql/data
volumes:
  posada_pgdata:
